"""Split addon into addon and addonVersion

Revision ID: 2001a587ce37
Revises: 2d307f19ba93
Create Date: 2025-02-18 22:45:41.056382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2001a587ce37"
down_revision: Union[str, None] = "2d307f19ba93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_addon_versions",
        sa.Column("addon_id", sa.BIGINT(), nullable=True),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.Column("secret", sa.String(), nullable=True),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["addon_id"], ["service_addons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_addon_versions_created_at"),
        "service_addon_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_addon_versions_id"), "service_addon_versions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_service_addon_versions_updated_at"),
        "service_addon_versions",
        ["updated_at"],
        unique=False,
    )
    op.add_column("service_addons", sa.Column("name", sa.String(), nullable=False))
    op.add_column("service_addons", sa.Column("description", sa.String(), nullable=False))
    op.add_column(
        "service_addons", sa.Column("depends", postgresql.ARRAY(sa.String()), nullable=False)
    )
    op.add_column(
        "service_addons", sa.Column("authors", postgresql.ARRAY(sa.String()), nullable=False)
    )
    op.drop_column("service_addons", "meta")
    op.drop_column("service_addons", "secret")
    op.drop_column("service_addons", "path")
    op.drop_column("service_addons", "encrypted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_addons", sa.Column("encrypted", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "service_addons", sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "service_addons", sa.Column("secret", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "service_addons",
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("service_addons", "authors")
    op.drop_column("service_addons", "depends")
    op.drop_column("service_addons", "description")
    op.drop_column("service_addons", "name")
    op.drop_index(op.f("ix_service_addon_versions_updated_at"), table_name="service_addon_versions")
    op.drop_index(op.f("ix_service_addon_versions_id"), table_name="service_addon_versions")
    op.drop_index(op.f("ix_service_addon_versions_created_at"), table_name="service_addon_versions")
    op.drop_table("service_addon_versions")
    # ### end Alembic commands ###
