"""add tokens and user addons count

Revision ID: 41af6b6e66b8
Revises: a02c851ebd8c
Create Date: 2025-02-04 22:33:59.085079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41af6b6e66b8"
down_revision: Union[str, None] = "a02c851ebd8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_tokens",
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("owner_id", sa.BIGINT(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["service_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_tokens_body"), "service_tokens", ["body"], unique=True)
    op.create_index(
        op.f("ix_service_tokens_created_at"), "service_tokens", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_service_tokens_id"), "service_tokens", ["id"], unique=False)
    op.create_index(
        op.f("ix_service_tokens_updated_at"), "service_tokens", ["updated_at"], unique=False
    )
    op.add_column(
        "service_users", sa.Column("addons", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_users", "addons")
    op.drop_index(op.f("ix_service_tokens_updated_at"), table_name="service_tokens")
    op.drop_index(op.f("ix_service_tokens_id"), table_name="service_tokens")
    op.drop_index(op.f("ix_service_tokens_created_at"), table_name="service_tokens")
    op.drop_index(op.f("ix_service_tokens_body"), table_name="service_tokens")
    op.drop_table("service_tokens")
    # ### end Alembic commands ###
