"""add addon_id column

Revision ID: dfe96eae99f1
Revises: 41af6b6e66b8
Create Date: 2025-02-11 19:17:31.146973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfe96eae99f1"
down_revision: Union[str, None] = "41af6b6e66b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_addons", sa.Column("addon_id", sa.String(), nullable=False))
    op.create_unique_constraint("service_addons_addon_id_key", "service_addons", ["addon_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("service_addons_addon_id_key", "service_addons", type_="unique")
    op.drop_column("service_addons", "addon_id")
    # ### end Alembic commands ###
