"""Change addon secret type to string

Revision ID: 2d307f19ba93
Revises: dfe96eae99f1
Create Date: 2025-02-18 02:41:21.992550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d307f19ba93"
down_revision: Union[str, None] = "dfe96eae99f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_addons",
        "secret",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Do not downgrade this changes
    op.alter_column(
        "service_addons",
        "secret",
        existing_type=sa.String(),
        type_=postgresql.BYTEA(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
    """
